
export const ADD_CONTACT = 'ADD_CONTACT';
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR';
export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS';

export const CONTACTS_LIST = 'CONTACTS_LIST';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';

export const LIST_CONVERSATION_USER = 'LIST_CONVERSATION_USER';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
